// Auto-generated by scripts/split-manual.cjs
// Do not edit manually.

import introSource from './intro.md?raw';
import loginSource from './login.md?raw';
import colaboradoresSource from './colaboradores.md?raw';
import vacacionesSource from './vacaciones.md?raw';
import asistenciaSource from './asistencia.md?raw';
import solicitudesSource from './solicitudes.md?raw';
import notificacionesSource from './notificaciones.md?raw';
import proyectosSource from './proyectos.md?raw';
import clientesSource from './clientes.md?raw';
import tareoSource from './tareo.md?raw';
import indicadoresSource from './indicadores.md?raw';
import evaluacionesSource from './evaluaciones.md?raw';
import configuracionesSource from './configuraciones.md?raw';
import faqsSource from './faqs.md?raw';

export const introContent = introSource;
export const faqContent = faqsSource;

export const moduleContents: Record<string, string> = {
  login: loginSource,
  colaboradores: colaboradoresSource,
  vacaciones: vacacionesSource,
  asistencia: asistenciaSource,
  solicitudes: solicitudesSource,
  notificaciones: notificacionesSource,
  proyectos: proyectosSource,
  clientes: clientesSource,
  tareo: tareoSource,
  indicadores: indicadoresSource,
  evaluaciones: evaluacionesSource,
  configuraciones: configuracionesSource,
};
